services:
  database:
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: disysuser
      POSTGRES_PASSWORD: disyspw
      POSTGRES_DB: disysdb
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
